### ISSUE TITLE
explain private

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ruby-enumerable-comparable#5]
"private means you can't call (foo) below line (number)

**Comment by jrhorn424** [comment]
Good catch. 😉

**Comment by gaand** [comment]
@J-Weeks @jrhorn424 Would one or both of you please explain this issue?  Thanks.

**Comment by RealWeeks** [comment]
@gaand In the original teaching of this lesson private was used and it lead to some student confusion.

**Comment by jrhorn424** [comment]
It was something like this:

``` ruby
class Foo
  def bar
    "baz"
  end
  private :bar

  def qux
    bar # this works
  end
end

Foo.new.bar # this does not work
```

I believe this can be closed. @J-Weeks @gaand

**Comment by gaand** [comment]
I didn't use it last time (although I should have done).

Your example captures the meaning.

I am not sure if it's actually in the repo, so something to prompt its use other than memory?

**Comment by jrhorn424** [comment]
Yep. Maybe even adding something like my example above would be enough.

**Comment by RealWeeks** [comment]
@jrhorn424 @gaand Please feel free to close if discussion is over.  Don't want to close mid-conversation.

**Comment by jrhorn424** [comment]
It's not closable if it isn't addressed.

**Comment by jrhorn424** [comment]
This should be mentioned when building the deck.
