### ISSUE TITLE
Don't use super

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ruby-enumerable-comparable#7]
Haven't gone over inheritance until after this training. via @gaand

**Comment by gaand** [comment]
I've waffled on this, but I think the Array should be in the Deck, not its parent.

**Comment by jrhorn424** [comment]
I agree with @gaand. The collection should be inside the Deck.

**Comment by gaand** [comment]
Closed in f7962c816eb163ca019e52a55f67df9164c09fa9

Commit message said `Close #6` in error.
