### ISSUE TITLE
Do Lab Before Reading Documentation

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby-enumerable-comparable#9]
Per @jrhorn424 
He wants to have them do the Lab before reading the Ruby Documentation in the future...

**Comment by gaand** [comment]
@jrhorn424 I believe 17eb14dbe5286f48fba4508ae113d3a038cc0221 should close this.

Please let me know if so.

**Comment by jrhorn424** [comment]
Awesome. Thanks!
